"""DuckDB loading utilities for synthetic pricing data."""

from collections.abc import Sequence

from duckdb import DuckDBPyConnection

from pricing_agent.data.pipeline import PipelineOutput


def _insert_rows(
    connection: DuckDBPyConnection,
    table: str,
    columns: tuple[str, ...],
    values: Sequence[Sequence[object]],
) -> None:
    """Insert multiple rows into a database table.

    Args:
        connection: Open DuckDB connection.
        table: Name of the target database table.
        columns: Column names to populate.
        values: Rows to insert into the table.
    """
    column_names = ", ".join(columns)
    placeholders = ", ".join("?" for _ in columns)

    query = f"""
        INSERT INTO {table} ({column_names})
        VALUES ({placeholders})
    """

    connection.executemany(query, values)


def load_pipeline_output(
    connection: DuckDBPyConnection,
    output: PipelineOutput,
) -> None:
    """Load synthetic pipeline output into DuckDB tables.

    Args:
        connection: Open and initialized DuckDB connection.
        output: Synthetic data generated by the pricing pipeline.
    """
    connection.begin()

    try:
        _insert_rows(
            connection,
            table="weekly_conditions",
            columns=("week", "demand_index"),
            values=list(
                zip(
                    output["weekly_conditions"]["week"],
                    output["weekly_conditions"]["demand_index"],
                )
            ),
        )

        _insert_rows(
            connection,
            table="users",
            columns=("user_id", "signup_week", "segment", "channel", "tier"),
            values=list(
                zip(
                    output["users"]["user_id"],
                    output["users"]["signup_week"],
                    output["users"]["segment"],
                    output["users"]["channel"],
                    output["users"]["tier"],
                )
            ),
        )

        _insert_rows(
            connection,
            table="weekly_price",
            columns=("week", "price"),
            values=list(
                zip(
                    output["weekly_prices"]["week"],
                    output["weekly_prices"]["price"],
                )
            ),
        )

        _insert_rows(
            connection,
            table="assigned_prices",
            columns=("user_id", "observed_price", "is_randomized"),
            values=list(
                zip(
                    output["assigned_prices"]["user_id"],
                    output["assigned_prices"]["observed_price"],
                    output["assigned_prices"]["is_randomized"],
                )
            ),
        )

        _insert_rows(
            connection,
            table="conversion_probabilities",
            columns=("user_id", "conversion_probability"),
            values=list(
                zip(
                    output["conversion_probabilities"]["user_id"],
                    output["conversion_probabilities"]["conversion_probability"],
                )
            ),
        )

        _insert_rows(
            connection,
            table="conversion_outcomes",
            columns=("user_id", "conversion_outcome"),
            values=list(
                zip(
                    output["conversion_outcomes"]["user_id"],
                    output["conversion_outcomes"]["conversion_outcome"],
                )
            ),
        )

        _insert_rows(
            connection,
            table="acquisition_costs",
            columns=("user_id", "acquisition_cost"),
            values=list(
                zip(
                    output["acquisition_costs"]["user_id"],
                    output["acquisition_costs"]["acquisition_cost"],
                )
            ),
        )

        _insert_rows(
            connection,
            table="marginal_costs",
            columns=("user_id", "marginal_cost"),
            values=list(
                zip(
                    output["marginal_costs"]["user_id"],
                    output["marginal_costs"]["marginal_cost"],
                )
            ),
        )

        _insert_rows(
            connection,
            table="churn_probabilities",
            columns=("user_id", "churn_probability"),
            values=list(
                zip(
                    output["churn_probabilities"]["user_id"],
                    output["churn_probabilities"]["churn_probability"],
                )
            ),
        )

        _insert_rows(
            connection,
            table="churn_outcomes",
            columns=("user_id", "churn_outcome"),
            values=list(
                zip(
                    output["churn_outcomes"]["user_id"],
                    output["churn_outcomes"]["churn_outcome"],
                )
            ),
        )

        connection.commit()

    except Exception:
        connection.rollback()
        raise
